!classDefinition: #Carlos category: #'Actividad 1'!
DenotativeObject subclass: #Carlos
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Actividad 1'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Carlos class' category: #'Actividad 1'!
Carlos class
	instanceVariableNames: ''!

!Carlos class methodsFor: 'as yet unclassified' stamp: 'GR 8/31/2020 22:05:14'!
hola
	"Saludo"

	^'Hello World'! !
